[[redirects]]
  from = "/pricing"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/converter"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/recipes"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/profile"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
